//Bubblesort
#include<stdio.h>
#include<conio.h>
void main()
{
	int a[5],i,j,temp;
	clrscr();

	printf("Enter 5 numbers:\n");
	for(i=0;i<5;i++)
		scanf("%d",&a[i]);
	printf("array:\n");
	for(i=0;i<5;i++)
		printf("%d ",a[i]);

	for(i=0;i<5;i++)
	{
		for(j=i+1;j<5;j++)
		{
			if(a[i]>a[j])
			{
				temp=a[i];
				a[i]=a[j];
				a[j]=temp;
			}
		}
	}

	printf("\nSorted Array:\n");
	for(i=0;i<5;i++)
		printf("%d ",a[i]);
	getch();
}